<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>AutoFacingChairs</AssemblyName>
    <RootNamespace>AutoFacingChairs</RootNamespace>
    <OutputPath>../../Assemblies/</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="AutoFacingChairs.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.4871" />
    <PackageReference Include="Lib.Harmony.Ref" Version="2.3.6" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net472" Version="1.0.3" PrivateAssets="all" />
    <PackageReference Update="FSharp.Core" Version="4.7.2" ExcludeAssets="runtime" />
  </ItemGroup>
</Project>
